name: hello-world
on: push
jobs:
  checklist:
    runs-on: self-hosted
    steps:
      - name: Check Docker
        run: docker version 
      - name: Check Java 
        run: java -version && javac -version
      - name: Check Maven 
        run: mvn -version
      - name: Check Python3 
        run: python3 --version
      - name: Check Terrafrom 
        run: terraform version
      - name: Check Ansible 
        run: ansible --version
